### ISSUE TITLE
'session_run.RunSummary.txt' does not exist in current working directory

### ISSUE THREAD

**Issue by steve-real** [DanChaltiel/nih.joinpoint#1]
Hi Dan, 
Trying to use your excellent package but keep getting the following error: "'session_run.RunSummary.txt' does not exist in current working directory".
What would you recommend me to do?

**Comment by DanChaltiel** [comment]
Hi Steve,
Thanks for the feedback.
Could you post the exact code that you ran?
If you could share a data sample (even obfuscated) so I can reproduce the error on my computer that would be very helpful too.

**Comment by steve-real** [comment]
Here you go! And thank you for your quick reply.

```
#JOINTPOINT IN R #####

#devtools::install_github("DanChaltiel/nih.joinpoint")

library(tidyverse)
library(nih.joinpoint)
options(joinpoint_path="C:/Program Files (x86)/Joinpoint/Joinpoint.exe")

sample_data %>% group_by(sex) %>% slice(1, 2, n()-1, n()) #first 2 and last 2 of each group

jp2 = joinpoint(sample_data, x=year, y=rate)

#FROM JOINPOINT 4.9.0
# #---------------------------
# Error
# ---------------------------
#   Joinpoint cannot open this type of file.
# ---------------------------
#   OK   
# ---------------------------
#FROM R version 4.2.0
#Error: 'session_run.RunSummary.txt' does not exist in current working directory ('C:/Users/AppData/Local/Temp/Rtmp6PJj97/joinpoint 2022-07-20 12h36m09s').

```

**Comment by DanChaltiel** [comment]
OK, did it work when you ran it with options? (using `run_options(), as in the main example)
Did you check the folder in the error output? Is there anything inside it?
I just ran the same code and I have no error yet, but the code is taking very long I'm still waiting for it to finish.

**Comment by steve-real** [comment]
- It didn't work with run_options() either.
- I did find the folder. It is among my temp files. This could maybe contribute to joinpoint not being able to find/read them?
- The folder contained the correct dataset; "dataset.txt" (with the additional "session_run.ini" and a folder named "ini" folder). However, there is no "session_run.RunSummary.txt" 
- I was actually never able to run the code (I waited several minutes before stopping it). I then realized that the joinpoint software was not open. Once the software was opened, I reran the code and that's when I started getting the error message posted above, from both the software and R.

**Comment by DanChaltiel** [comment]
> It didn't work with run_options() either.

I'm not sure I was clear enough, I was referring to the first example with `run_options()`:

```r
run_opt = run_options(model="ln", max_joinpoints=3, n_cores=3)
export_opt = export_options()
jp = joinpoint(sample_data, x=year, y=rate, by=sex, se=se,
               run_opt_ini=run_opt, export_opt_ini=export_opt)
```
Did you try this code exactly?
This example took 4 seconds to run on my computer with no error, but it could take longer on yours. How many cores do you have (`parallel::detectCores()`)?

>I waited several minutes before stopping it

Of course, if you stop the code, it won't work.
In fact, the code you posted took 20 minutes to run on my computer (6-cores i5-8400). 
This is quite expected because by default it runs on a single core with `max_joinpoints=4`; that's why we use `run_options()` to increase the number of cores and decrease the maximum joinpoints. I left the same default values as in the original joinpoint software.

>I did find the folder. It is among my temp files.

The folder in temp should have 11 files + the "ini" directory, so you didn't pass the point where the function actually calls the joinpoint software, which is expected if you stopped the code yourself. The folder is supposed to be in a temp file, this is normal.
You don't have to open the software for the code to work. I even wonder if there could be any interaction.

If you didn't run the first example, please try it and tell me. Otherwise, please run the code for at least 20-30 min before stopping.

**Comment by steve-real** [comment]
- I tried running it with run_opt(), as in your example, but I got the following error: 
```
Error in joinpoint(sample_data, x = year, y = rate, by = sex, se = se,  : 
  unused arguments (run_opt_ini = run_opt, export_opt_ini = export_opt)
```
In the R Documentation (i.e.,Help window), run_opt_ini is actually "run_opts", and export_opt_ini is "export_opts". 
`joinpoint(
  data,
  x,
  y,
  by = NULL,
  se = NULL,
  y_type = c("Age-Adjusted Rate", "Crude rate", "Percent", "Proportion", "Count"),
  export_opts = export_options(),
  run_opts = run_options(),
  cmd_path = getOption("joinpoint_path",
    "C:/Program Files (x86)/Joinpoint Command/jpCommand.exe"),
  dir = get_tempdir(),
  verbose = FALSE
)`
Once I changed it, I was able to run the code, but it still kept going without ever producing results (8-cores i7-10700 CPU @ 2.90GHz). Maybe it is due to my Joinpoint software?

- Also, should the Joinpoint software be opened or closed while I run the R version of joinpoint?
Thanks!

**Comment by DanChaltiel** [comment]
My bad, this package is still very early-stage and experimental, I recently changed the names of the arguments as you wrote but didn't update the example in the readme. I just made the correction.
Note that while the status is still maturing, this might happen sometimes if I find better names.
![image](https://camo.githubusercontent.com/ae2f538d678a8e76c5493d870c59fbf928b14906e41227a07af5bbf3566b5068/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6c6966656379636c652d6d61747572696e672d626c75652e737667)
(any feedback on the names is highly welcome BTW 👍)

Which version of joinpoint are you using? This package has been built for command-line v4.9.0.0. There is no way to check for the version programmatically yet, so I cannot enforce this check myself. I found the version number in the ReadMe.txt file that lies besides the software `.exe`.

The graphic interface of the joinpoint software is a totally different software than the command-line. It can be opened or closed with no interference.

Wait, are you sure you are using the command-line version (https://surveillance.cancer.gov/joinpoint/callable)? This will definitely never work if you are trying with the graphic interface.

**Comment by steve-real** [comment]
Well, I think you've found the problem. Now it's my turn to say "my bad": I should've read your README file more attentively.
I just requested a command-line version from the NIH so I can't confirm that it will work, but based on your code working, I am confident that the issue was on my side (i.e. using the graphic interface version) and not the code. This issue can be closed.
Thanks again for your time and assistance!
