### ISSUE TITLE
Missing run_summary Output in nih.joinpoint Package

### ISSUE THREAD

**Issue by Liu499-create** [DanChaltiel/nih.joinpoint#11]
**Describe the bug**
When using the nih.joinpoint package to perform Joinpoint analysis with the NIH Joinpoint software (Command-Line version 4.9.0.0), the output of names(jp) does not include "run_summary" as expected. According to the documentation, this element should be present. I would like to understand why this is happening and how to resolve it.

**Reproducible example**
structure(list(sex = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L), levels = c("Both", "Male", "Female"), class = "factor"), 
    year = c(1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 
    1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 
    1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 
    2003, 2004, 2005, 2006, 2007, 2008, 2009, 1975, 1976, 1977, 
    1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 
    1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 
    1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 
    2008, 2009, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 
    1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 
    1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 
    2003, 2004, 2005, 2006, 2007, 2008, 2009), rate = c(59.525154534, 
    61.354829038, 62.407366246, 62.043968385, 62.374363878, 63.750188608, 
    64.237128329, 62.783505361, 63.669770015, 64.81253559, 66.299378856, 
    64.183377214, 62.706918297, 61.357916313, 61.690574504, 60.699467697, 
    59.475817657, 58.000031025, 56.798426896, 55.618782424, 54.028570361, 
    54.7636255, 56.408002304, 56.758446595, 55.464621879, 54.12272701, 
    53.476329985, 53.051963577, 50.630380242, 49.629557532, 47.493800532, 
    46.519080142, 45.92279309, 44.680006566, 42.611542348, 68.438090728, 
    71.72298955, 73.491086797, 72.368366548, 74.113638163, 74.543045803, 
    75.834517274, 75.176459604, 75.591474907, 77.636837821, 79.154276734, 
    77.786382855, 77.476966627, 75.179529445, 74.956323249, 74.357007268, 
    72.887007482, 70.413804281, 68.435508621, 66.252016874, 63.813659921, 
    65.536025383, 68.092667142, 67.062970633, 65.706773083, 63.667489919, 
    62.866018181, 61.389268893, 59.317945266, 58.341696428, 54.962162329, 
    52.951528697, 52.855887419, 50.986779614, 48.23188506, 53.648341475, 
    54.142628476, 54.961589282, 55.256196698, 54.583795036, 56.541957659, 
    56.477279253, 54.506797008, 55.603620458, 56.077180714, 57.332921419, 
    54.706769686, 52.659984958, 51.794392476, 52.423238508, 51.277350754, 
    50.051266177, 49.205259632, 48.313470244, 47.721004126, 46.920725565, 
    46.692476007, 47.942512044, 49.274055488, 47.840620288, 46.744800946, 
    46.138841185, 46.556978929, 43.77254956, 42.934125135, 41.587999731, 
    41.340517596, 40.284199484, 39.499413206, 38.083517668), 
    se = c(0.622375554, 0.625778913, 0.626162862, 0.61576641, 
    0.611855116, 0.611369262, 0.608140947, 0.594746569, 0.592998413, 
    0.592247523, 0.592800951, 0.577918476, 0.565680008, 0.554826624, 
    0.551234683, 0.541403558, 0.530319599, 0.516397705, 0.505961653, 
    0.49569028, 0.483554327, 0.48267822, 0.485361214, 0.482658252, 
    0.473524296, 0.46424885, 0.458228865, 0.452781723, 0.438766946, 
    0.43121924, 0.417881423, 0.410786319, 0.404019708, 0.395299865, 
    0.382172535, 1.069193781, 1.076291096, 1.088909023, 1.068569033, 
    1.074041655, 1.064857304, 1.064131648, 1.050285891, 1.04086662, 
    1.041062662, 1.038014585, 1.020369803, 1.009959751, 0.984476928, 
    0.971126922, 0.957533065, 0.93394505, 0.902279907, 0.877691031, 
    0.851725613, 0.826681995, 0.827028166, 0.835840954, 0.820640008, 
    0.801746809, 0.780365006, 0.767909271, 0.750670986, 0.7297155, 
    0.718372041, 0.687036048, 0.66787584, 0.65805714, 0.639430754, 
    0.613868704, 0.769875107, 0.76731314, 0.765631693, 0.757244199, 
    0.74486984, 0.748807368, 0.742599798, 0.721160983, 0.721623669, 
    0.71917725, 0.719866928, 0.695900919, 0.677029816, 0.665691262, 
    0.664375089, 0.651475504, 0.637942166, 0.624609427, 0.612506806, 
    0.603210467, 0.593265654, 0.587327234, 0.590599798, 0.594005473, 
    0.581928655, 0.571217175, 0.56425259, 0.563822758, 0.543031117, 
    0.534637463, 0.522843064, 0.518445738, 0.507904108, 0.499745776, 
    0.487556723)), row.names = c(NA, -105L), class = c("tbl_df", 
"tbl", "data.frame"))
# Load necessary libraries
library(tidyverse)
library(nih.joinpoint)

# View data and perform initial visualization
ggplot(nih_sample_data, aes(x=year, y=rate, color=sex)) + geom_point() + geom_line()

# Set run and export options
run_opt = run_options(model="ln", max_joinpoints=3, n_cores=3)
export_opt = export_options(aapc_full_range = TRUE)

# Run Joinpoint analysis
jp = joinpoint(nih_sample_data, x=year, y=rate, by=sex, se=se, run_opts=run_opt, export_opts=export_opt)

# Check the names of the output object
names(jp)
#output of  names(jp):
[1] "aapc"           "apc"            "data_export"    "selected_model" "perm_test"      "report" 

**<summary>Session info</summary>**
<details>
``` r
 #Paste here the output of `sessionInfo()` here
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8  LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8 LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] nih.joinpoint_0.1.0.9003 lubridate_1.9.3          forcats_1.0.0            stringr_1.5.1           
 [5] dplyr_1.1.4              purrr_1.0.2              readr_2.1.5              tidyr_1.3.1             
 [9] tibble_3.2.1             ggplot2_3.5.1            tidyverse_2.0.0         

loaded via a namespace (and not attached):
 [1] bit_4.0.5         gtable_0.3.5      crayon_1.5.3      compiler_4.4.0    tidyselect_1.2.1  parallel_4.4.0   
 [7] snakecase_0.11.1  scales_1.3.0      lattice_0.22-6    R6_2.5.1          labeling_0.4.3    generics_0.1.3   
[13] patchwork_1.2.0   janitor_2.2.0     munsell_0.5.1     pillar_1.9.0      tzdb_0.4.0        rlang_1.1.3      
[19] utf8_1.2.4        stringi_1.8.4     bit64_4.0.5       timechange_0.3.0  cli_3.6.2         withr_3.0.1      
[25] magrittr_2.0.3    grid_4.4.0        vroom_1.6.5       rstudioapi_0.16.0 hms_1.1.3         lifecycle_1.0.4  
[31] vctrs_0.6.5       glue_1.7.0        farver_2.1.2      zoo_1.8-12        fansi_1.0.6       colorspace_2.1-1 
[37] tools_4.4.0       pkgconfig_2.0.3  
```
</details>

**Comment by DanChaltiel** [comment]
This is a problem of documentation.
The run summary should now be consulted using `summary(jp)`
