### ISSUE TITLE
about the file "session_run.RunSummary.txt" , it looks like that the file was created by the code,but it was never been found, i checked the R code and found it no where but a line where it serves as a inut file, could you please check this? thank you very much, best regards  

### ISSUE THREAD

**Issue by ZT-ls** [DanChaltiel/nih.joinpoint#2]
**Describe the bug**
Please be as clear and thorough as possible. If possible include the version of JoinPoint you are using.

**Reproducible example**
Share the code that caused the bug, along with all error and warning messages.
Please also use `dput(df)` to provide a sample dataset so I can reproduce the error. If your dataset is too large, select a minimal number of columns and rows, or use https://pastebin.com/.

**<summary>Session info</summary>**
<details>
``` r
 #Paste here the output of `sessionInfo()` here
```
</details>

**Comment by DanChaltiel** [comment]
It seems you didn't even take the time to read the text that you posted and put everything in the title.
I cannot help you with so little information.

**Comment by ZT-ls** [comment]
sorry for the title thing, my bad.  i found it would be the same issue as descripted in another  closed one, it may be about the software version,
