### ISSUE TITLE
run_opt creates an empty file and the run_options()'s default has not valid values.

### ISSUE THREAD

**Issue by cbalzani** [DanChaltiel/nih.joinpoint#3]
Hi, Dan.
Thank you for your effort and for sharing your code with the community.
I am trying to use your package, but I got an error as a return for the run_options function. Would you mind helping me out?

Some important information for your reference:
- Not using the graphic interface of the joinpoint software. I installed the command-line version. 
- The version number in the ReadMe.txt file that lies beside the software .exe is Joinpoint 4.9.0.0 Command.
- I ran the example you provided on the README file as it is.

### **1st try: run_opt creates an empty file**
Running your code as it is, the run_opt object return as an empty character representation. The same thing happens with export_opt.

![image](https://github.com/DanChaltiel/nih.joinpoint/assets/67658359/8e43776b-36a4-41aa-b7d0-3a4a65282231)

![image](https://github.com/DanChaltiel/nih.joinpoint/assets/67658359/cfe2fbca-dd22-46d8-8150-0368407ef934)

### **2nd try: default has non-valid values**
Based on R Help Window, I edited the run_options() function to run the code with default options. The run_opt object is not empty anymore, but it gets not valid values.

`run_opt = run_options(
  model = "ln",
  data_shift = 0,
  min_joinpoints = 0,
  max_joinpoints = 3,
  pairwise = NULL,
  pairwise_signif_lvl = 0.05,
  pairwise_n_permut = 4499,
  method = "grid",
  min_obs_end = 2,
  min_obs_between = 2,
  n_obs_between = 0,
  model_selection_method = "permutation test",
  permutation_signif_lvl = 0.05,
  n_permutations = 4499,
  early_stopping = "b-value",
  run_type = "provided",
  rates_per_n = 1e+05,
  dependent_variable_type = "percent",
  het_error = "standard error",
  het_error_var_location = NULL,
  ci_method = "parametric",
  n_cores = 3,
  delay_type = "non-delay",
  autocorr_errors = "number",
  jump_model = FALSE,
  comparability_ratio = FALSE,
  include_std_analysis = FALSE,
  jump_location = 9999,
  comparability_ratio_value = 0,
  cr_variance = 0,
  joinpoint_alpha_lvl = 0.05,
  apc_alpha_lvl = 0.05,
  aapc_alpha_lvl = 0.05,
  jump_cr_alpha_lvl = 0.05,
  random_seed = 7160,
  empirical_quantile_seed = 10000,
  empirical_quantile_seed_type = "constant",
  n_resample = 1000,
  madwd = FALSE,
  madwd_psi = 0
)`

![image](https://github.com/DanChaltiel/nih.joinpoint/assets/67658359/e3ea21b6-2c32-4ca0-9511-d16e2026735b)

![image](https://github.com/DanChaltiel/nih.joinpoint/assets/67658359/f0e22df7-ab22-449a-a5a5-7e173f1f594f)

**Comment by DanChaltiel** [comment]
Hi C,

Thanks for your well-written feedback. 

Unfortunately, I wasn't able to reproduce your error.

On my computer (Win10, R4.1.3), `run_options()` returns a nonempty glue/character object, as intended:
``` r
library(nih.joinpoint)
run_opt = run_options(model="ln", max_joinpoints=3, n_cores=3)
run_opt
#> [Session Options]
#> Model=ln
#> Maximum joinpoints=3
#> Num cores=3
```

<sup>Created on 2023-06-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Could you start a new R session, run the minimal code to reproduce your error, and then share the output of `sessionInfo()`? 
If you can use `reprex::reprex(session_info=TRUE)` that would be even better (see [here](https://reprex.tidyverse.org/articles/magic-reprex.html) if you don't know about it), but it sometimes doesn't work with packages like this one.

Also, a `joinpoint_error.txt` file should have been created, could you post the content as well?

On second thought, the most probable is that one dependency is outdated on your compuer. Could you update all the packages in the "imports" of https://github.com/DanChaltiel/nih.joinpoint/blob/main/DESCRIPTION and see if that fixes your problem?

**Comment by cbalzani** [comment]
Hi, Dan

Thank you very much for your quick reply and apologies for my late feedback.
Your second thought was precise! I updated all the "imports" packages and the code worked perfectly.

Got this issue fixed!

I will try to run it with my own data now. Thanks a lot ~ 😊
