### ISSUE TITLE
How to display different groups in the same chart

### ISSUE THREAD

**Issue by superrray** [DanChaltiel/nih.joinpoint#6]
I am writing to seek your advice on a problem I am facing with a chart generating program from your source code library. My dataset has multiple groups and I would like to display them all in the same chart.

I have tried merging the data for each group into a single data frame and then using the plotting function in your code to create the chart. However, this approach is not suitable for my data as different groups have different attributes and proportions, and combining them would definitely result in loss of information.

Is there a feasible way to display the data for each group in the same chart while still retaining their unique characteristics? I would like to leverage your tool as it fits my requirements very well.

Thank you for your kind assistance.

**Comment by DanChaltiel** [comment]
Hi @superrray,
In order to help you, I will need a reproducible example, including a dataset, the expected output, and if possible some code to start from.
You can also try to explain your problem and expected output using the examples from the README.

**Comment by superrray** [comment]
Hi Dan，
Thank you for your reply.
I noticed that jp_plot  defaults to presenting independent graphs for each group. I would like to present two groups on the same graph to better express my data, such as a graph that puts male and female groups together. I have tried your source code many times, but my R level is limited. Could you teach me how to quickly modify the code so that male and female groups can be presented on the same graph？

**Comment by DanChaltiel** [comment]
Hi @superrray,
I'll repeat my previous message: 
>In order to help you, I will need a reproducible example, including a dataset, the expected output, and if possible some code to start from.
>You can also try to explain your problem and expected output using the examples from the README.

**Comment by DanChaltiel** [comment]
Or maybe you are just looking for `by_levels`?
There is now an example in the Readme but there was a bug so you will need to update the package.

**Comment by DanChaltiel** [comment]
Closing this issue as stale
